rules:
  import/no-unresolved: error
  import/named: error
  # import/default: error
  import/namespace: error
  import/export: error

  import/no-named-as-default: warn
  # import/no-named-as-default-member: warn
  import/no-duplicates: warn
  import/first: warn
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
      newlines-between: never
  import/no-useless-path-segments: error
  import/no-self-import: error
  import/no-absolute-path: error
  import/no-commonjs: error
  import/no-amd: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      peerDependencies: false
      optionalDependencies: false

  import/exports-last: warn
  # import/group-exports: warn
  # import/no-default-export: error
  import/no-mutable-exports: error
  import/no-named-default: error
